In [1]:
import pandas as pd

In [15]:
df_1 = pd.read_excel('pokemon_data.xlsx')
df_1

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [19]:
df_2 = pd.read_csv('pokemon_data.txt', delimiter='\t')
df_2

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [20]:
df = pd.read_csv('pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [11]:
# top 5 lines
df.head(5)
# last 5 lines
df.tail(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

# Reading data in Pandas

In [21]:
# read headers
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [30]:
# read each column
df.Name[0:3]
df['Name'][0:3]
df[['Name', 'HP', 'Legendary']][0:3]

        Name  HP  Legendary
0  Bulbasaur  45      False
1    Ivysaur  60      False
2   Venusaur  80      False

In [43]:
# read each column
df.iloc[0]
df.iloc[1:4]
df.iloc[2,1]

# access only the rows that have df as specified
df.loc[df['Type 1']=='Rock']

# iterate through rows
for index, row in df.iterrows():
    print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 FlabÃ©bÃ©
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [44]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [51]:
# sorting
df.sort_values('HP')
df.sort_values('Name', ascending=False)
df.sort_values(['Type 1', 'HP'])
df.sort_values(['Type 1', 'HP'], ascending = [1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

# Making changes to the data

In [53]:
df['total'] = df['HP'] + df['Attack'] + df['Defense']

In [76]:
df

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,670.0,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,False,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,503.0,False,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,1001.0,True,50,100,150,100,150,50,6
796,719,DiancieMega Diancie,Rock,Fairy,1181.0,True,50,160,110,160,110,110,6
797,720,HoopaHoopa Confined,Psychic,Ghost,1001.0,True,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,Dark,1151.0,True,80,160,60,170,130,80,6
799,721,Volcanion,Fire,Water,1041.0,True,80,110,120,130,90,70,6

In [55]:
df = df.drop(columns = ['total'])

In [71]:
df['Total'] = df.iloc[:, 4:10].sum(axis=1)

In [75]:
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

# Saving our data

In [78]:
df.to_csv('modified.csv', index=False)

In [79]:
df.to_excel('modified.xlsx', index=False)

In [80]:
df.to_csv('modified.txt', index=False, sep='\t')

# Filtering data

In [84]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,670.0,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,False,80,100,123,122,120,80,1
48,43,Oddish,Grass,Poison,545.0,False,45,50,55,75,65,30,1
49,44,Gloom,Grass,Poison,675.0,False,60,65,70,85,75,40,1
50,45,Vileplume,Grass,Poison,840.0,False,75,80,85,110,90,50,1
75,69,Bellsprout,Grass,Poison,530.0,False,50,75,35,70,30,40,1
76,70,Weepinbell,Grass,Poison,680.0,False,65,90,50,85,45,55,1
77,71,Victreebel,Grass,Poison,840.0,False,80,105,65,100,70,70,1
344,315,Roselia,Grass,Poison,655.0,False,50,60,45,100,80,65,3
451,406,Budew,Grass,Poison,435.0,False,40,30,35,50,70,55,4
452,407,Roserade,Grass,Poison,835.0,False,60,70,65,125,105,90,4
651,590,Foongus,Grass,Poison,518.0,False,69,55,45,55,55,15,5
652,591,Amoonguss,Grass,Poison,818.0,False,114,85,70,85,80,30,5

In [96]:
df.loc[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,670.0,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,False,80,100,123,122,120,80,1
16,13,Weedle,Bug,Poison,320.0,False,40,35,30,20,20,50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,543.0,False,56,61,65,48,45,38,6
719,651,Quilladin,Grass,NaN,695.0,False,61,78,95,56,58,57,6
720,652,Chesnaught,Grass,Fighting,921.0,False,88,107,122,74,75,64,6
740,672,Skiddo,Grass,NaN,591.0,False,66,65,48,62,57,52,6
741,673,Gogoat,Grass,NaN,913.0,False,123,100,62,97,81,68,6

In [113]:
new = df.loc[((df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')) & (df['HP'] > 70)]
new

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,False,80,100,123,122,120,80,1
50,45,Vileplume,Grass,Poison,840.0,False,75,80,85,110,90,50,1
77,71,Victreebel,Grass,Poison,840.0,False,80,105,65,100,70,70,1
79,73,Tentacruel,Water,Poison,810.0,False,80,70,65,80,120,100,1
111,103,Exeggutor,Grass,Psychic,920.0,False,95,95,85,125,65,55,1
168,154,Meganium,Grass,NaN,870.0,False,80,82,100,83,100,80,2
197,182,Bellossom,Grass,NaN,830.0,False,75,80,95,90,100,50,2
204,189,Jumpluff,Grass,Flying,715.0,False,75,55,70,55,95,110,2
207,192,Sunflora,Grass,NaN,735.0,False,75,75,55,105,85,30,2
298,275,Shiftry,Grass,Dark,820.0,False,90,100,60,90,60,80,3
390,357,Tropius,Grass,Flying,782.0,False,99,68,83,72,87,51,3
433,388,Grotle,Grass,NaN,709.0,False,75,89,85,55,65,36,4
434,389,Torterra,Grass,Ground,909.0,False,95,109,105,75,85,56,4
505,455,Carnivine,Grass,NaN,790.0,False,74,100,72,90,72,46,4
510,460,Abomasnow,Grass,Ice,843.0,False,90,92,75,92,85,60,4
511,460,AbomasnowMega Abomasnow,Grass,Ice,1053.0,False,90,132,105,132,105,30,4
516,465,Tangrowth,Grass,NaN,970.0,False,100,100,125,110,50,50,4
550,492,ShayminLand Forme,Grass,NaN,1001.0,True,100,100,100,100,100,100,4
551,492,ShayminSky Forme,Grass,Flying,999.0,True,100,103,75,120,75,127,4
556,497,Serperior,Grass,NaN,848.0,False,75,75,95,75,95,113,5
571,512,Simisage,Grass,NaN,832.0,False,75,98,63,98,63,101,5
617,556,Maractus,Grass,NaN,795.0,False,75,86,67,106,67,60,5
652,591,Amoonguss,Grass,Poison,818.0,False,114,85,70,85,80,30,5
659,598,Ferrothorn,Grass,Steel,842.0,False,74,94,131,54,116,20,5
701,640,Virizion,Grass,Fighting,924.0,True,91,90,72,90,129,108,5
720,652,Chesnaught,Grass,Fighting,921.0,False,88,107,122,74,75,64,6
741,673,Gogoat,Grass,NaN,913.0,False,123,100,62,97,81,68,6

# Reset index

In [115]:
new = new.reset_index(drop=True)
print(new)

      #                     Name Type 1    Type 2   Total  Legendary   HP  \
0     3                 Venusaur  Grass    Poison   870.0      False   80
1     3    VenusaurMega Venusaur  Grass    Poison  1050.0      False   80
2    45                Vileplume  Grass    Poison   840.0      False   75
3    71               Victreebel  Grass    Poison   840.0      False   80
4    73               Tentacruel  Water    Poison   810.0      False   80
5   103                Exeggutor  Grass   Psychic   920.0      False   95
6   154                 Meganium  Grass       NaN   870.0      False   80
7   182                Bellossom  Grass       NaN   830.0      False   75
8   189                 Jumpluff  Grass    Flying   715.0      False   75
9   192                 Sunflora  Grass       NaN   735.0      False   75
10  275                  Shiftry  Grass      Dark   820.0      False   90
11  357                  Tropius  Grass    Flying   782.0      False   99
12  388                   Grotle  Grass       NaN   709.0      False   75
13  389                 Torterra  Grass    Ground   909.0      False   95
14  455                Carnivine  Grass       NaN   790.0      False   74
15  460                Abomasnow  Grass       Ice   843.0      False   90
16  460  AbomasnowMega Abomasnow  Grass       Ice  1053.0      False   90
17  465                Tangrowth  Grass       NaN   970.0      False  100
18  492        ShayminLand Forme  Grass       NaN  1001.0       True  100
19  492         ShayminSky Forme  Grass    Flying   999.0       True  100
20  497                Serperior  Grass       NaN   848.0      False   75
21  512                 Simisage  Grass       NaN   832.0      False   75
22  556                 Maractus  Grass       NaN   795.0      False   75
23  591                Amoonguss  Grass    Poison   818.0      False  114
24  598               Ferrothorn  Grass     Steel   842.0      False   74
25  640                 Virizion  Grass  Fighting   924.0       True   91
26  652               Chesnaught  Grass  Fighting   921.0      False   88
27  673                   Gogoat  Grass       NaN   913.0      False  123

    Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0       82       83      100      100     80           1
1      100      123      122      120     80           1
2       80       85      110       90     50           1
3      105       65      100       70     70           1
4       70       65       80      120    100           1
5       95       85      125       65     55           1
6       82      100       83      100     80           2
7       80       95       90      100     50           2
8       55       70       55       95    110           2
9       75       55      105       85     30           2
10     100       60       90       60     80           3
11      68       83       72       87     51           3
12      89       85       55       65     36           4
13     109      105       75       85     56           4
14     100       72       90       72     46           4
15      92       75       92       85     60           4
16     132      105      132      105     30           4
17     100      125      110       50     50           4
18     100      100      100      100    100           4
19     103       75      120       75    127           4
20      75       95       75       95    113           5
21      98       63       98       63    101           5
22      86       67      106       67     60           5
23      85       70       85       80     30           5
24      94      131       54      116     20           5
25      90       72       90      129    108           5
26     107      122       74       75     64           6
27     100       62       97       81     68           6

# Regex Filtering

In [120]:
import re

In [121]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,670.0,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
4,4,Charmander,Fire,NaN,503.0,False,39,52,43,60,50,65,1
5,5,Charmeleon,Fire,NaN,665.0,False,58,64,58,80,65,80,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,1011.0,True,108,100,121,81,95,95,6
795,719,Diancie,Rock,Fairy,1001.0,True,50,100,150,100,150,50,6
797,720,HoopaHoopa Confined,Psychic,Ghost,1001.0,True,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,Dark,1151.0,True,80,160,60,170,130,80,6
799,721,Volcanion,Fire,Water,1041.0,True,80,110,120,130,90,70,6

In [122]:
df.loc[df['Type 1'].str.contains('Fire|Grass', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,670.0,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,False,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,503.0,False,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,612.0,False,62,50,58,73,54,72,6
736,668,Pyroar,Fire,Normal,842.0,False,86,68,72,109,66,106,6
740,672,Skiddo,Grass,NaN,591.0,False,66,65,48,62,57,52,6
741,673,Gogoat,Grass,NaN,913.0,False,123,100,62,97,81,68,6
799,721,Volcanion,Fire,Water,1041.0,True,80,110,120,130,90,70,6

In [127]:
# all pokemon names starting with pi
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
20,16,Pidgey,Normal,Flying,411.0,False,40,45,40,35,35,56,1
21,17,Pidgeotto,Normal,Flying,577.0,False,63,60,55,50,50,71,1
22,18,Pidgeot,Normal,Flying,787.0,False,83,80,75,70,70,101,1
23,18,PidgeotMega Pidgeot,Normal,Flying,957.0,False,83,80,80,135,80,121,1
30,25,Pikachu,Electric,NaN,500.0,False,35,55,40,50,50,90,1
136,127,Pinsir,Bug,NaN,845.0,False,65,125,100,55,70,85,1
137,127,PinsirMega Pinsir,Bug,Flying,1005.0,False,65,155,120,65,90,105,1
186,172,Pichu,Electric,NaN,315.0,False,20,40,15,35,35,60,2
219,204,Pineco,Bug,NaN,530.0,False,50,65,90,35,35,15,2
239,221,Piloswine,Ice,Ground,790.0,False,100,100,80,60,60,50,2
438,393,Piplup,Water,NaN,532.0,False,53,51,53,61,56,40,4
558,499,Pignite,Fire,Fighting,726.0,False,90,93,55,70,55,55,5
578,519,Pidove,Normal,Flying,455.0,False,50,55,50,36,30,43,5

# Conditional Changes

In [131]:
df.loc[df['Type 1'] == 'Fire', 'Type 1']='Flamer'
df

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,670.0,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,870.0,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,False,80,100,123,122,120,80,1
4,4,Charmander,Flamer,NaN,503.0,False,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,1001.0,True,50,100,150,100,150,50,6
796,719,DiancieMega Diancie,Rock,Fairy,1181.0,True,50,160,110,160,110,110,6
797,720,HoopaHoopa Confined,Psychic,Ghost,1001.0,True,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,Dark,1151.0,True,80,160,60,170,130,80,6
799,721,Volcanion,Flamer,Water,1041.0,True,80,110,120,130,90,70,6

In [143]:
df.loc[df['Name'].str.contains('[a-z]*saur', flags=re.I, regex=True), ['Legendary', 'Generation']] = ['test 1', 'test 2']
df.loc[df['Name'].str.contains('[a-z]*saur')]

,#,Name,Type 1,Type 2,Total,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,526.0,test 1,45,49,49,65,65,45,test 2
1,2,Ivysaur,Grass,Poison,670.0,test 1,60,62,63,80,80,60,test 2
2,3,Venusaur,Grass,Poison,870.0,test 1,80,82,83,100,100,80,test 2
3,3,VenusaurMega Venusaur,Grass,Poison,1050.0,test 1,80,100,123,122,120,80,test 2

# Aggregate Statistics

In [153]:
df.groupby(['Type 1']).mean()
df.groupby(['Type 1', 'Type 2']).count()['#']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: #, Length: 136, dtype: int64

# Working with large amount of data

In [158]:
for df in pd.read_csv('modified.csv', chunksize=5):
    
    res = df.groupby(['Type 1', 'Type 2']).count()
print(res)

                #  Name  Total  Legendary  HP  Attack  Defense  Sp. Atk  \
Type 1  Type 2
Fire    Water   1     1      1          1   1       1        1        1
Psychic Dark    1     1      1          1   1       1        1        1
        Ghost   1     1      1          1   1       1        1        1
Rock    Fairy   2     2      2          2   2       2        2        2

                Sp. Def  Speed  Generation
Type 1  Type 2
Fire    Water         1      1           1
Psychic Dark          1      1           1
        Ghost         1      1           1
Rock    Fairy         2      2           2

# Nominatim

In [1]:
pip install geopy

Requirement already satisfied: geopy in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from geopy) (1.52)
Note: you may need to restart the kernel to use updated packages.

In [1]:
#To geolocate a query to an address and coordinates:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent='user_agent')
location = geolocator.geocode("London")

print(location.address)
print('\n', (location.latitude, location.longitude))

London, Greater London, England, United Kingdom

 (51.5073219, -0.1276474)

In [3]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent='user_agent')
location = geolocator.geocode("Chitradurga")
print(location.address)
print('\n', (location.latitude, location.longitude))

Chitradurga, Chitradurga taluku, Chitradurga district, Karnataka, 577500, India

 (14.2266443, 76.4005122)

In [6]:
from geopy.distance import geodesic
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent='user_agent')

a = geolocator.geocode("Junagadh")
b = geolocator.geocode("Sagar")
am = (a.latitude, a.longitude)
destb = (b.latitude, b.longitude)
print(geodesic(am, destb).km)

c = geolocator.geocode("Karimganj")
d = geolocator.geocode("Pathanamthitta")
destc = (c.latitude, c.longitude)
destd = (d.latitude, d.longitude)
print(geodesic(destc, destd).km)

e = geolocator.geocode("Nagapattinam")
f = geolocator.geocode("Kalaburagi")
deste = (e.latitude, e.longitude)
destf = (f.latitude, f.longitude)
print(geodesic(deste, destf).km)

a = geolocator.geocode("Rewa")
b = geolocator.geocode("Datia")
am = (a.latitude, a.longitude)
destb = (b.latitude, b.longitude)
print(geodesic(am, destb).km)

889.3004255507698
2370.6580657248387
763.4966887529649
336.3290081513469

In [166]:
#To find the address corresponding to a set of coordinates:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent='user_agent')
location = geolocator.reverse("52.509669, 13.376294")
print(location.address)
print('\n', (location.latitude, location.longitude))

Potsdamer Platz, Tiergarten, Mitte, Berlin, 10785, Deutschland

 (52.5098014, 13.375589791291057)

In [170]:
from functools import partial
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent='user_agent')

geocode = partial(geolocator.geocode, language='es')
print(geocode('London'))

geocode = partial(geolocator.geocode, language='en')
print(geocode('London'))

reverse = partial(geolocator.reverse, language='es')
print(reverse("52.509669, 13.376294"))

Londres, Greater London, Inglaterra, Reino Unido
London, Greater London, England, United Kingdom
Potsdamer Platz, Tiergarten, Mitte, BerlÃ­n, 10785, Alemania

# Wikipedia

In [174]:
import wikipedia as w

In [175]:
w.summary("Wikipedia")

"Wikimedia Foundation, Inc. (WMF, or simply Wikimedia) is a 501(c)(3) nonprofit organization headquartered in San Francisco, California, registered as a charitable foundation under US law. It owns the Wikimedia projects â€“ which are written and curated by thousands of Wikipedians and other unpaid volunteers â€“ and the MediaWiki wiki software.The Wikimedia Foundation was established in 2003 in St. Petersburg, Florida, by Jimmy Wales as a non-profit way to fund Wikipedia, Wiktionary, and other crowdsourced wiki projects which had until then been hosted by Bomis, Wales' for-profit company. The Foundation finances itself mainly through millions of small donations from Wikipedia readers, collected through email campaigns and annual fundraising banners placed on Wikipedia. These are complemented by grants from various tech companies and philanthropic organizations. \nThe Foundation has grown rapidly throughout its existence. By 2021, it employed over 550 staff and contractors, with annual revenues in excess of US$160 million, annual expenses of around US$110 million, and a growing endowment, which surpassed US$100 million in June 2021."

In [176]:
w.search('Barack') # does a Wikipedia search for a query

['Barack Obama',
 'Barack Obama Sr.',
 'Barack (disambiguation)',
 'Presidency of Barack Obama',
 'Early life and career of Barack Obama',
 'Family of Barack Obama',
 'Barack (name)',
 'Barack Obama religion conspiracy theories',
 'Barack Obama presidential campaign',
 'Barack (brandy)']

In [178]:
w.suggest('Barack Obama')# returns the suggested Wikipedia title for a query, or None

In [179]:
w.search('apple', results=5)

['Apple', 'Apple Inc.', 'Apple (disambiguation)', 'MacOS', 'IOS']

In [182]:
w.summary('world') # to get the summary of an article

'In its most general sense, the term "world" refers to the totality of entities, to the whole of reality or to everything that is. The nature of the world has been conceptualized differently in different fields. Some conceptions see the world as unique while others talk of a "plurality of worlds". Some treat the world as one simple object while others analyze the world as a complex made up of many parts. In scientific cosmology the world or universe is commonly defined as "[t]he totality of all space and time; all that is, has been, and will be". Theories of modality, on the other hand, talk of possible worlds as complete and consistent ways how things could have been. Phenomenology, starting from the horizon of co-given objects present in the periphery of every experience, defines the world as the biggest horizon or the "horizon of all horizons". In philosophy of mind, the world is commonly contrasted with the mind as that which is represented by the mind. Theology conceptualizes the world in relation to God, for example, as God\'s creation, as identical to God or as the two being interdependent. In religions, there is often a tendency to downgrade the material or sensory world in favor of a spiritual world to be sought through religious practice. A comprehensive representation of the world and our place in it, as is commonly found in religions, is known as a worldview. Cosmogony is the field that studies the origin or creation of the world while eschatology refers to the science or doctrine of the last things or of the end of the world.\nIn various contexts, the term "world" takes a more restricted meaning associated, for example, with the Earth and all life on it, with humanity as a whole or with an international or intercontinental scope. In this sense, world history refers to the history of humanity as a whole or world politics is the discipline of political science studying issues that transcend nations and continents. Other examples include terms such as "world religion", "world language", "world government", "world war", "world population", "world economy" or "world championship".'

In [190]:
# w.summary('Venus', sentences=1) # returns PageError since page doesn't exist
# m = w.summary('Mercury', sentences=1) # returns DisambiguationError
try:
    v = w.summary('Venus', sentences=1)
    m = w.summary('Mercury', sentences=1)
except w.exceptions.PageError as e:
    print(e)
except wikipedia.exceptions.DisambiguationError as e:
    print(e.options)

['Mercury (planet)', 'Mercury (element)', 'Mercury (mythology)', 'Mercury (toy manufacturer)', 'Mercury Communications', 'Mercury Drug', 'Mercury Energy', 'Mercury Filmworks', 'Mercury General', 'Mercury Interactive', 'Mercury Marine', 'Mercury Systems', 'Mercury (programming language)', 'Mercury (metadata search system)', 'Ferranti Mercury', 'Mercury Browser', 'Mercury Mail Transport System', 'Mercury (film)', 'Mercury (TV series)', 'Young Adult', 'character in the RWBY web series', 'Sailor Mercury', 'Mercury (Marvel Comics)', 'Makkari (comics)', 'Metal Men', "Cerebro's X-Men", 'Amalgam Comics character', 'Mercury (magazine)', 'The Mercury (Hobart)', 'The Mercury (South Africa)', 'The Mercury (Pennsylvania)', 'Mercury (Newport)', 'List of newspapers named Mercury', 'Mercury (Bova novel)', 'Mercury (Livesey novel)', 'Anna Kavan', 'Mercury Nashville', 'Mercury Records', 'Mercury Prize', 'The Planets', 'Mercury (American Music Club album)', 'Mercury (Longview album)', 'Mercury (Madder Mortem album)', 'Mercury â€“ Act 1', 'Mercury â€“ Act 2', '"Mercury" (song)', 'Recovering the Satellites', 'Failer', 'Planetarium', 'Operation Mercury', 'Boeing E-6 Mercury', 'Miles Mercury', 'HMS\xa0Mercury', 'USS\xa0Mercury', 'Russian brig\xa0Mercury', 'Mercury (pigeon)', 'Mercury (name)', 'Mercury, Savoie', 'Mercury Bay', 'place in Alabama', 'Mercury, Nevada', 'Mercury, Texas', 'Mercury (plant)', 'Annual mercury', 'Blitum bonus-henricus', 'Mercury FM', 'Heart Hertfordshire', 'Edmonton Mercurys', 'Fujita Soccer Club Mercury', 'Memphis Mercury', 'Phoenix Mercury', 'Toledo Mercurys', 'Blackburn Mercury', 'Bristol Mercury', 'Mercury (automobile)', 'Mercury (cyclecar)', 'Mercury (train)', 'Mercury\xa0(ship)', 'Cape Cod Mercury 15', 'Mercury 18', "Archer Maclean's Mercury", 'Mercury (cipher machine)', 'Mercury (satellite)', 'Mercury Boulevard', 'Mercury Cinema', 'Project Mercury', 'Shuttle America', 'The Mercury Mall', 'All pages with titles beginning with Mercury ', 'The American Mercury', 'Mercuri', 'Mercury 1 (disambiguation)', 'Mercury 2 (disambiguation)', 'Mercury 3 (disambiguation)', 'Mercury 4 (disambiguation)', 'Mercury 5 (disambiguation)', 'Mercury 6 (disambiguation)', 'Mercury 7 (disambiguation)', 'Mercury 8 (disambiguation)', 'Mercury City (disambiguation)', 'Mercury FM (disambiguation)', 'Mercury House (disambiguation)', 'Mercury mission (disambiguation)', 'Mercury program (disambiguation)', 'Mercury project (disambiguation)', 'All pages with titles containing Mercury']

In [220]:
import pandas as pd

try:
    ap = w.page('Apple') # load and access data from full Wikipedia pages
    
    html = ap.html().encode('UTF-8')
    df = pd.read_html(html)[2]
    print(df)
        
    print(ap, ap.title)
    
    print(ap.url)
    
    w.set_lang('es')
    
    print('no. of images: ', len(ap.images))
    
    print(ap.content)
    
    print(ap.references)
    
except w.exceptions.DisambiguationError as e:
    print(e.options)

                         Lista de productos de Apple
0  Primeras computadoras[editar] Apple I (1976) A...
<WikipediaPage 'Apple'> Apple
https://es.wikipedia.org/wiki/Apple
no. of images:  38
Apple, Inc. es una empresa estadounidense que diseÃ±a y produce equipos electrÃ³nicos, software y servicios en lÃ­nea. Tiene su sede central en el Apple Park, en Cupertino (California, Estados Unidos) y la sede europea en la ciudad de Cork (Irlanda).[3]â€‹ Sus productos de hardware incluyen el telÃ©fono inteligente iPhone, la tableta iPad, la computadora personal Mac, el reproductor de medios portÃ¡til iPod, el reloj inteligente Apple Watch y el reproductor de medios digitales Apple TV. Entre el software de Apple se encuentran los sistemas operativos iOS, iPadOS, macOS, watchOS y tvOS, el explorador de contenido multimedia iTunes, la suite iWork (software de productividad), Final Cut Pro X (una suite de ediciÃ³n de vÃ­deo profesional), Logic Pro (software para ediciÃ³n de audio en pistas de audio), Xsan (software para el intercambio de datos entre servidores) y el navegador web Safari.
La empresa operaba, en mayo de 2014, mÃ¡s de 408 tiendas propias en nueve paÃ­ses,[4]â€‹ miles de distribuidores (destacÃ¡ndose los distribuidores prÃ©mium o Apple Premium Resellers) y una tienda en lÃ­nea (disponible en varios paÃ­ses) donde se venden sus productos y se presta asistencia tÃ©cnica. De acuerdo con la revista Fortune, Apple fue la empresa mÃ¡s llamativa en el mundo entre 2008 y 2012.[5]â€‹ En 2015, se convirtiÃ³ en la empresa mÃ¡s valiosa del mundo segÃºn el Ã­ndice BrandZ al alcanzar los 247 000 millones de euros de valor.[6]â€‹ El 3 de agosto de 2018, segÃºn The Wall Street Journal, la compaÃ±Ã­a se convirtiÃ³ en la primera empresa en lograr una capitalizaciÃ³n de mercado de 2 billÃ³n (mil millardos) de dÃ³lares. en el 2020, su  valor se estimaba en unos 2,500 billones de dÃ³lares.[7]â€‹ y al 3 de enero de 2022, rebasaba la cifra de los 3 billones de dÃ³lares.[8]â€‹
Las dos primeras tiendas Apple Inc abrieron en los Estados Unidos en 2001. En 2003, ampliÃ³ su red en JapÃ³n, con la apertura de la primera tienda fuera de los EE.UU. Esto fue seguido por la apertura de tiendas en el: Reino Unido, CanadÃ¡, Italia, Australia, Alemania, BÃ©lgica, Suecia, Francia, PaÃ­ses Bajos, EspaÃ±a, TurquÃ­a, Singapur, Corea del Sur, EAU y RepÃºblica Popular China. En IberoamÃ©rica cuenta con tiendas en: Argentina, Brasil y MÃ©xico.


== Historia ==


=== 1976-1980: FundaciÃ³n e incorporaciÃ³n ===

Steve Wozniak y Steve Jobs se conocieron en 1971, cuando un amigo mutuo, Bill FernÃ¡ndez, presentÃ³ a Wozniak, quien tenÃ­a 21 aÃ±os de edad, a Jobs, entonces de 15 aÃ±os. Steve Wozniak, a quien le gustaba que le llamaran Woz, siempre habÃ­a sentido una gran atracciÃ³n por la electrÃ³nica en general, diseÃ±ando desde que era pequeÃ±o circuitos en papel para despuÃ©s tratar de optimizarlos al mÃ¡ximo. Dada su aficiÃ³n por la electrÃ³nica, Woz "apadrinaba" a otros chicos a los que les gustase el tema, como Bill FernÃ¡ndez, o el mismo Steve Jobs.
Pronto Wozniak empezÃ³ a dedicar cada vez mÃ¡s y mÃ¡s tiempo a construir en papel su propia computadora. Tras intentos relativamente infructuosos en su oficina de trabajo en Hewlett-Packard (sus jefes vieron el proyecto y no estaban interesados y le autorizaron a continuarlo),[9]â€‹ finalmente sus esfuerzos dieron como resultado lo que serÃ­a la Apple I. Tras la presentaciÃ³n de su computadora en el club informÃ¡tico Homebrew Computer Club y asombrar a sus participantes,[10]â€‹ Jobs rÃ¡pidamente vio la oportunidad de negocio, por lo que empezÃ³ a promover la computadora entre otros aficionados de la informÃ¡tica del Homebrew Computer Club y otras tiendas de electrÃ³nica digital.
Al poco tiempo empezaron a recibir pequeÃ±os encargos de computadoras que construÃ­an ellos mismos con mÃ¡quinas hechas a mano, llegando a vender unos 200 ejemplares de su mÃ¡quina Apple I. El 1 de abril de 1976 fue fundada Apple Computer a travÃ©s de un contrato firmado por sus tres accionistas: Steve Wozniak, Steve Jobs y Ron Wayne,[11]â€‹ este Ãºltimo antiguo compaÃ±ero de trabajo de Jobs en la empresa Atari,[12]â€‹ y con apenas 10 % de la nueva empresa.[13]â€‹ Doce dÃ­as despuÃ©s de la fundaciÃ³n Wayne vende sus acciones por US$800 y pasado el tiempo el contrato original que Ã©l mismo firmÃ³ por US$500.[14]â€‹ Dicho contrato luego se subastÃ³ el 13 de diciembre de 2011 en Nueva York, el cual tuvo como base un valor inicial de entre 100 y 150 mil dÃ³lares,[15]â€‹ pero que alcanzÃ³ finalmente un valor venta de 1,59 millones de dÃ³lares.[16]â€‹ Se les unieron mÃ¡s amigos, pero las prestaciones del Apple I eran limitadas, asÃ­ que empezaron a buscar financiaciÃ³n. Finalmente, Jobs conociÃ³ a Mike Markkula, que accediÃ³ a invertir 250 000 USD.
En total, se produjeron y se vendieron alrededor de doscientas unidades a 666.66 USD la unidad,[17]â€‹ pero el Ã©xito fue tal que no pudieron dar abasto a tanta demanda. Las caracterÃ­sticas del Apple I eran limitadas por el poco dinero del que disponÃ­an Jobs y Wozniak. De hecho, para construir el prototipo, Jobs tuvo que vender su camioneta y Woz su calculadora programable HP.


==== El Apple II y el Ã©xito ====

Con el dinero ganado gracias a la venta del Apple I, en Apple pudo comenzar a pensar en una mÃ¡quina bastante mÃ¡s ambiciosa: el Apple II. Para Wozniak, el Apple II iba a ser simplemente la computadora que hubiera querido construir si no hubiera tenido las limitaciones econÃ³micas que tuvo con el Apple I. Tuvo la idea de incluir en el equipo memoria de vÃ­deo para administrar la visualizaciÃ³n en color, del mismo modo que incluÃ­a numerosas tarjetas de expansiÃ³n de modo que los usuarios pudieran ampliar las capacidades de la computadora segÃºn sus propias necesidades.
Con el diseÃ±o del primer prototipo del Apple II reciÃ©n terminado, Apple decidiÃ³ asistir al festival informÃ¡tico Personal Computing Festival, un nuevo certamen. AllÃ­, la incipiente industria de la microinformÃ¡tica podÃ­a mostrar sus progresos y hacer negocio y contactos. En el vuelo a Filadelfia, lugar donde se celebrara en 1976, los fundadores de Apple coincidieron en el aviÃ³n con los fundadores de Processor Technology y su reciÃ©n diseÃ±ada computadora Sol, coincidencia que tuvo un gran impacto en el futuro inmediato de Apple.
La gran mayorÃ­a de mÃ¡quinas y empresas dedicadas a la microinformÃ¡tica en 1976, y por consiguiente prÃ¡cticamente todas las que formaban el festival, eran en general jÃ³venes fanÃ¡ticos de la informÃ¡tica con kits que los usuarios debÃ­an montar y/o soldar para poder hacer funcionar, por lo tanto enfocadas sobre todo a los entusiastas de la electrÃ³nica. Sin embargo, Processor Technology ofrecÃ­a una imagen mucho mÃ¡s seria y profesional, y su Sol era una computadora que si bien estaba enfocado, al igual que los demÃ¡s, como un kit que debÃ­a montarse, tambiÃ©n se daba la posibilidad de adquirirla como computadora ya montado y listo para utilizar.
Fue entonces cuando Steve Jobs comprendiÃ³ que el futuro no estaba en placas con componentes que los usuarios debieran montar y soldar ellos mismos, sino en computadoras como el Sol, ya montadas y preparadas para el uso y disfrute de los usuarios. Por lo tanto, el Apple II, el cual aÃºn no habÃ­a salido a la venta, debÃ­a incorporar la salida de vÃ­deo, el teclado y todo aquello que necesitara en una caja de plÃ¡stico para hacer que su uso fuera mÃ¡s sencillo.

Si bien Steve Wozniak era el diseÃ±ador de toda la lÃ³gica y la electrÃ³nica del Apple II, Steve Jobs era el creador del concepto y la visiÃ³n de futuro de Apple, buscando al mismo tiempo la forma de crear un producto que pudiera satisfacer a todos los usuarios, y no solo a los mÃ¡s tÃ©cnicos. Aparte de la decisiÃ³n de vender el Apple II como un conjunto perfectamente empaquetado, otras importantes decisiones suyas fueron la de invertir en mejores sistemas de alimentaciÃ³n elÃ©ctrica y control del calentamiento del equipo, siendo el Apple II una computadora completamente silenciosa gracias a que no necesitaba ventiladores para controlar su temperatura.
Pero concebir tal mÃ¡quina suponÃ­a mucho dinero y un personal calificado, algo que no tenÃ­an. NingÃºn banco querÃ­a arriesgarse en tal proyecto, y menos en aquellos tiempos: una computadora utilizable por el gran pÃºblico parecÃ­a absurdo en la Ã©poca, puesto que los bienes posibles de los habitantes, eran escasos para comprar este tipo de tecnologÃ­a. Ronald Wayne, que habÃ­a ayudado a Jobs y Wozniak a concebir el Apple I, era escÃ©ptico sobre las oportunidades de Ã©xito de tal proyecto y abandonÃ³ a la compaÃ±Ã­a. Jobs conociÃ³ finalmente a Mike Markkula[18]â€‹ en 1977, quien aportÃ³ su peritaje en asuntos y un cheque de US$250 000 al capital de Apple. TambiÃ©n proporcionÃ³ en esa ocasiÃ³n su primer Presidente a Apple, Mike Scott.
El modelo final de Apple II se presentÃ³ al pÃºblico en abril de 1977 convirtiÃ©ndose en el canon de lo que debÃ­a ser a partir de entonces una computadora personal. Por este motivo, Apple cambiÃ³ su logotipo por el famoso logo de la manzana coloreada, que recordaba que el Apple II era una de las primeras computadoras en disponer de monitor en color.
Otras teorÃ­as aseguran que el logo fue en honor al matemÃ¡tico y precursor de la informÃ¡tica Alan Turing, fallecido tras morder una manzana.[19]â€‹
A mediados de 1979, Apple presentÃ³ el Apple II+, una evoluciÃ³n del Apple II dotada, en particular, con mÃ¡s memoria (48 KiB ampliable a 64 KiB) y lenguaje de programaciÃ³n BASIC.
Gran parte del Ã©xito de Apple se basaba en que fue una computadora realizada para gustar tanto a los expertos hackers como al pÃºblico mÃ¡s profano en tÃ©rminos de informÃ¡tica. Pronto, la base de software para el Apple II comenzÃ³ a crecer, haciendo mÃ¡s atractivo la computadora al resto del pÃºblico, en especial cuando apareciÃ³ en el mercado la primera hoja de cÃ¡lculo de la historia, la VisiCalc, la cual hizo vender ella sola miles de computadoras Apple II.


==== Computadoras posteriores ====

Mientras que el Apple II conocÃ­a un Ã©xito creciente, Apple ya trabaja en sus sucesores. Lisa debÃ­a ser una evoluciÃ³n del Apple II, una mÃ¡quina de transiciÃ³n antes de Lisa y Macintosh que serÃ­an una nueva clase de equipos. Para el sucesor del Apple II, Steve Jobs querÃ­a una mÃ¡quina mÃ¡s avanzada aÃºn para contribuir al mercado de la informÃ¡tica de empresa. Los ingenieros debÃ­an ajustarse a objetivos muy ambiciosos o incluso a veces casi irrealizables (un tema recurrente en la historia de Apple), sobre todo teniendo en cuenta que el perÃ­odo de desarrollo de esta mÃ¡quina era corto (algo menos de un aÃ±o). Aunque las ventas del Apple II eran mÃ¡s fuertes que nunca, Apple pensaba que estas empezarÃ­an a bajar pronto, por lo que serÃ­a necesario presentar a su sucesor lo mÃ¡s rÃ¡pidamente posible.
La computadora fue presentada finalmente en mayo de 1980 bajo el nombre de Apple III. Desgraciadamente, algunas elecciones tÃ©cnicas, entre las cuales se encontraba la ausencia de un ventilador, fueron la razÃ³n de que muchos equipos se sobrecalentaran.[20]â€‹ Miles de Apple III debieron sustituirse. Algunos meses mÃ¡s tarde, en noviembre de 1981, Apple lanzÃ³ una nueva versiÃ³n del Apple III, que corregÃ­a todos los grandes problemas de la versiÃ³n inicial. Un Apple III+ saliÃ³ incluso en 1983. Pero los problemas de sus comienzos desalentaron a los compradores y fueron la razÃ³n de que el Apple III se convirtiera en el primer gran fracaso comercial de Apple. Solo se habÃ­an vendido 65 000 equipos a final de verano, mientras que Apple pensaba vender millones como el Apple II. Los equipos que salieron en los aÃ±os siguientes llevaban el nombre de Apple II (IIe en enero de 1983, IIc en 1984, etc.) para olvidar los sinsabores del Apple III.
Pese al fracaso del Apple III, Apple aÃºn tenÃ­a dos modelos a desarrollar: Lisa y Macintosh. La gran apuesta de Apple era Lisa, la cual debÃ­a convertirse en la nueva generaciÃ³n de computadoras de Apple y con el que se pretendÃ­a tambiÃ©n atacar el mercado empresarial que se le habÃ­a negado con el Apple III y que sin embargo estaba siendo abarcado por la IBM PC, mientras que la Macintosh era un proyecto iniciado por Jef Raskin para construir una pequeÃ±a computadora muy econÃ³mica y fÃ¡cil de usar pensada para el mercado domÃ©stico.

Apple Lisa estaba pensado para ser la nueva generaciÃ³n de computadoras, y para conseguirlo no se reparÃ³ en gastos. Se incluyÃ³ en el modelo final un monitor, dos unidades de disquete, un disco duro de 5 megabytes (algo inmenso para la Ã©poca) y todo un megabyte (1 MiB) de RAM. Sin embargo, lo que primero saltaba a la vista no eran todas estas caracterÃ­sticas, sino la GUI, su novedosa interfaz de usuario basada en iconos que se activaban apuntando con una flecha controlada por un curioso dispositivo denominado ratÃ³n o mouse.
El 12 de diciembre de 1980, Apple entrÃ³ en la bolsa de valores. Hasta ese momento, solamente algunos de los empleados de Apple poseÃ­an acciones de la empresa. En unos minutos, los 4,6 millones de acciones se vendieron a 22 dÃ³lares la unidad, aumentando instantÃ¡neamente en 100 millones de dÃ³lares el capital de Apple. Al mismo tiempo, decenas de empleados de Apple se convirtieron en millonarios.[21]â€‹
Pese a los Ã©xitos econÃ³micos y la expansiÃ³n a nivel mundial de la empresa, 1981 fue un aÃ±o bastante duro para Apple. Aparte de los problemas del Apple III, en febrero de este aÃ±o, se decidiÃ³ purgar la plantilla de empleados; por lo que autorizÃ³ la despedida de 40 trabajadores de Apple (en total, la empresa superaba los 1000 empleados). Al mes siguiente, el purgado esta vez fue el mismo presidente, Scott, siendo reemplazado por Mike Markkula y asumiendo Steve Jobs el cargo de director (chairman).
El 12 de agosto salÃ­a al mercado la principal amenaza a la hegemonÃ­a de Apple, el IBM PC. Pese a que no era una mÃ¡quina muy innovadora, la imagen de marca de IBM le otorgaba un gran atractivo en el sector empresarial, por lo que se convirtiÃ³ en un fulgurante Ã©xito.
Mike Markkula relevÃ³ a Steve Jobs del equipo Lisa, acusÃ¡ndole de administrar mal al equipo (el proyecto se retrasarÃ­a por estos cambios). Jobs se puso a trabajar sobre el proyecto Macintosh. El Lisa saliÃ³ finalmente a principios de 1983, y se convirtiÃ³ en la primera computadora personal con interfaz grÃ¡fica y mouse. A pesar de su carÃ¡cter revolucionario, Lisa se vendiÃ³ muy mal, debido principalmente a su elevado precio: 10 000 USD. Mientras Apple sufrÃ­a los fracasos del Apple III y de Lisa, Mike Markkula dimitiÃ³ de la direcciÃ³n de Apple en 1983. El puesto de Presidente se propuso a John Sculley, entonces vicepresidente de Pepsi. En un primer momento rechazÃ³ el puesto; para convencerlo Steve Jobs le planteÃ³ esta profunda pregunta: Â«Â¿Prefiere pasar el resto de su vida vendiendo agua azucarada o tener la oportunidad de cambiar el mundo?Â». John Sculley aceptÃ³ finalmente y se convirtiÃ³ en el tercer Presidente de Apple.


=== Batalla legal contra Apple Corps ===
En 1978, Apple Corps denunciarÃ­a a Apple Inc. por infracciÃ³n de marcas registradas. El juicio fue visto para sentencia en 1981 con el pago de 80 000 dÃ³lares a Apple Corps. Como condiciÃ³n, Apple Computer aceptaba no inmiscuirse en el mercado musical. En 1989, se desarrollarÃ­a otra batalla legal, alegando Apple Corps que las mÃ¡quinas creadas por Apple Computer podÃ­an reproducir archivos en formato MIDI, infringiendo los tÃ©rminos del anterior litigio. En 1991 se alcanzarÃ­a otro acuerdo previo pago de 26,5 millones de dÃ³lares.
En septiembre de 2003, Apple Computer era nuevamente denunciada por Apple Corps, esta vez por crear la tienda musical iTunes y el iPod, que Apple Corps vio como una violaciÃ³n de los Ãºltimos acuerdos en los que Apple Inc. acordaba no distribuir mÃºsica. El juicio comenzÃ³ el 29 de marzo de 2006 en el Reino Unido, siendo visto para sentencia el 8 de mayo de 2006, con Apple Corps perdiendo el caso.
El 5 de febrero de 2007, Apple Inc. y Apple Corps anunciaron un acuerdo en su disputa por las marcas registradas en la que Apple Inc. preservaba el derecho sobre todas las marcas relacionadas con Â«AppleÂ». El acuerdo cierra la batalla legal entre ambas compaÃ±Ã­as, en la que ambas partes pagaban sus respectivos costes legales y en la que Apple Inc. podrÃ­a seguir usando el nombre y logotipo en iTunes. El acuerdo incluÃ­a acuerdos y tÃ©rminos confidenciales. Hoy dÃ­a, Apple Inc. ha anunciado un acuerdo para poder distribuir la mÃºsica de los Beatles en su tienda musical iTunes.


=== 1981-1989: Ã‰xito con el Macintosh ===

Tras el fracaso del Apple III y el Apple Lisa, la compaÃ±Ã­a se volcÃ³ en el pequeÃ±o proyecto de Jef Raskin primero y Steve Jobs despuÃ©s: el Macintosh. Tras numerosos retrasos y problemas, especialmente con el software, el cual no estuvo preparado hasta prÃ¡cticamente el Ãºltimo momento, y tras la emisiÃ³n de un destacado anuncio de televisiÃ³n durante la celebraciÃ³n del Super Bowl de ese aÃ±o, comercial dirigido por Ridley Scott y considerada el mejor comercial de televisiÃ³n de la dÃ©cada de 1980 por Advertising Age,[22]â€‹ la computadora fue presentada el 24 de enero de 1984.
Las previsiones de venta iniciales de medio millÃ³n de unidades vendidas hasta fin de aÃ±o parecÃ­an que podrÃ­an cumplirse durante los primeros meses de 1984, pero poco a poco las ventas se fueron ralentizando, provocando el pÃ¡nico en Apple.
Entre los muchos motivos que hicieron erosionarse las ventas del Macintosh, se puede destacar el alto precio (2495 USD), la escasa memoria RAM instalada en la computadora (solamente 128 KiB), la inclusiÃ³n de una Ãºnica unidad de disco, la no inclusiÃ³n de puertos de expansiÃ³n y la falta de software, ya que, salvo Apple, solamente Microsoft acudiÃ³ a la cita del Mac con productos de software.
Pero no solamente las ventas de Macintosh se reducÃ­an, sino tambiÃ©n el hasta ahora sustento de la compaÃ±Ã­a, el Apple II, empezaba a mostrar el desgaste de los aÃ±os. En Apple se decidiÃ³ unificar los proyectos de Lisa y Macintosh en uno solo, presentando la computadora Apple Lisa como un Macintosh de gama alta (pese a tener un procesador mÃ¡s lento).
Sin embargo, dicha unificaciÃ³n no hizo mÃ¡s que generar tensiones dentro de la propia Apple, ya que por un lado el grupo encargado del Apple II se veÃ­a completamente desplazado pese a que era el Ãºnico econÃ³micamente rentable, y por el otro tanto el grupo de desarrollo del Lisa como del Macintosh tenÃ­an filosofÃ­as de trabajo muy distintas, asÃ­ como condiciones salariales y, especialmente, sueldos, pues en algunas ocasiones, se retenÃ­an los pagos a los empleados.[cita requerida]La suerte del equipo cambiÃ³ con la introducciÃ³n de la primera impresora lÃ¡ser PostScript, la LaserWriter, que se ofrecerÃ­a a un precio razonable, y que junto con PageMaker y el propio Macintosh crearon el concepto de Â«AutoediciÃ³nÂ». El Mac fue particularmente fuerte en este mercado debido a sus capacidades grÃ¡ficas avanzadas, estas capacidades eran parte de su intuitiva interfaz grÃ¡fica de usuario.
En 1985, se generÃ³ una lucha de poder entre Steve Jobs y el consejero delegado John Sculley, que habÃ­a sido contratado por el propio Jobs dos aÃ±os antes. Jobs no estaba dispuesto a ser relegado a un puesto irrelevante en la compaÃ±Ã­a que fundÃ³ (su oficina fue trasladada a un edificio casi desierto en el campus de Apple al que Jobs llamaba Siberia)[23]â€‹ y comenzÃ³ a conspirar con los ejecutivos de Apple para hacerse con el control. Sculley se enterÃ³ de que Jobs habÃ­a estado tratando de organizar un golpe de estado y convocÃ³ a una reuniÃ³n de la junta el 10 de abril de 1985, en la cual, la junta directiva de Apple se puso unÃ¡nimemente del lado de Sculley y Jobs fue retirado de sus funciones como gestor. Unas semanas despuÃ©s Jobs abandonÃ³ Apple y fundÃ³ NeXT Inc. ese mismo aÃ±o.[24]â€‹


=== Greenpeace y Apple ===

In [219]:
w.donate() # opens the donations page of the Wikimedia project

# tabula

In [ ]:
!pip install tabula-py
import tabula

# pandas_profiling

In [13]:
! pip show pandas-profiling

Name: pandas-profiling
Version: 2.9.0
Summary: Generate profile report for pandas DataFrame
Home-page: https://github.com/pandas-profiling/pandas-profiling
Author: Simon Brugman
Author-email: pandasprofiling@gmail.com
License: MIT
Location: c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages
Requires: visions, htmlmin, requests, numpy, tqdm, ipywidgets, jinja2, attrs, joblib, scipy, matplotlib, seaborn, phik, confuse, missingno, pandas, tangled-up-in-unicode
Required-by:

In [2]:
pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

Collecting https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
  Downloading https://github.com/pandas-profiling/pandas-profiling/archive/master.zip (21.8 MB)
Requirement already satisfied: joblib~=1.1.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (1.1.0)
Requirement already satisfied: scipy>=1.4.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (1.7.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (1.4.3)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (3.4.3)
Requirement already satisfied: pydantic>=1.8.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (1.9.1)
Requirement already satisfied: PyYAML>=5.0.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from pandas-profiling==3.2.0) (5.4.1)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from pandas-profiling==3.2.0) (2.11.3)
Collecting visions[type_image_path]==0.7.5
  Downloading visions-0.7.5-py3-none-any.whl (102 kB)
Requirement already satisfied: numpy>=1.16.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (1.22.4)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (0.5.1)
Requirement already satisfied: phik>=0.11.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (0.12.2)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from pandas-profiling==3.2.0) (2.25.1)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (4.62.3)
Requirement already satisfied: seaborn>=0.10.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (0.11.2)
Requirement already satisfied: multimethod>=1.4 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas-profiling==3.2.0) (1.8)
Requirement already satisfied: networkx>=2.4 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->pandas-profiling==3.2.0) (2.6.3)
Requirement already satisfied: attrs>=19.3.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->pandas-profiling==3.2.0) (21.2.0)
Requirement already satisfied: imagehash in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->pandas-profiling==3.2.0) (4.2.1)
Requirement already satisfied: Pillow in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->pandas-profiling==3.2.0) (8.4.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jinja2>=2.11.1->pandas-profiling==3.2.0) (2.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling==3.2.0) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling==3.2.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling==3.2.0) (3.0.4)
Requirement already satisfied: cycler>=0.10 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling==3.2.0) (0.10.0)
Requirement already satisfied: six in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.2.0->pandas-profiling==3.2.0) (1.16.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling==3.2.0) (2022.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from pydantic>=1.8.1->pandas-profiling==3.2.0) (3.10.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling==3.2.0) (1.26.7)
Requirement already satisfied: idna<3,>=2.5 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from requests>=2.24.0->pandas-profiling==3.2.0) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling==3.2.0) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling==3.2.0) (2022.6.15)
Requirement already satisfied: colorama in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from tqdm>=4.48.2->pandas-profiling==3.2.0) (0.4.4)
Requirement already satisfied: PyWavelets in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from imagehash->visions[type_image_path]==0.7.5->pandas-profiling==3.2.0) (1.1.1)
Building wheels for collected packages: pandas-profiling
  Building wheel for pandas-profiling (setup.py): started
  Building wheel for pandas-profiling (setup.py): finished with status 'done'
  Created wheel for pandas-profiling: filename=pandas_profiling-3.2.0-py2.py3-none-any.whl size=262603 sha256=5f8eebb0d795e4526c12e839ce7ec36ef316ff0cccbdf11c7078e6e8ca5b1eaf
  Stored in directory: C:\Users\Riddhi Bhogaonkar\AppData\Local\Temp\pip-ephem-wheel-cache-vlnm7mzi\wheels\43\c8\f4\c0ebc32d7f20fe89d0e92d90eaeef5f0c0594a89b6bc16b352
Successfully built pandas-profiling
Installing collected packages: visions, pandas-profiling
  Attempting uninstall: visions
    Found existing installation: visions 0.5.0
    Uninstalling visions-0.5.0:
      Successfully uninstalled visions-0.5.0
  Attempting uninstall: pandas-profiling
    Found existing installation: pandas-profiling 2.9.0
    Uninstalling pandas-profiling-2.9.0:
      Successfully uninstalled pandas-profiling-2.9.0
Successfully installed pandas-profiling-3.2.0 visions-0.7.5
Note: you may need to restart the kernel to use updated packages.

In [9]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [5]:
import numpy as np
import pandas as pd

In [1]:
import pandas_profiling as pp

# Ignore

In [17]:
pip install MarkupSafe

Requirement already satisfied: MarkupSafe in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (2.0.1)Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install markupsafe==2.0.1

Requirement already satisfied: markupsafe==2.0.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (2.0.1)Note: you may need to restart the kernel to use updated packages.

In [19]:
pip install --user --upgrade aws-sam-cli

Collecting aws-sam-cliNote: you may need to restart the kernel to use updated packages.
  Downloading aws_sam_cli-1.52.0-py3-none-any.whl (5.1 MB)
Collecting tzlocal==3.0
  Downloading tzlocal-3.0-py3-none-any.whl (16 kB)
Collecting aws-sam-translator==1.46.0
  Downloading aws_sam_translator-1.46.0-py3-none-any.whl (231 kB)
Collecting aws-lambda-builders==1.17.0
  Downloading aws_lambda_builders-1.17.0-py3-none-any.whl (113 kB)
Requirement already satisfied: cookiecutter~=1.7.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-sam-cli) (1.7.2)
Collecting serverlessrepo==0.1.10
  Downloading serverlessrepo-0.1.10-py2.py3-none-any.whl (23 kB)
Collecting docker~=4.2.0
  Downloading docker-4.2.2-py2.py3-none-any.whl (144 kB)
Requirement already satisfied: MarkupSafe==2.0.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-sam-cli) (2.0.1)
Collecting dateparser~=1.0
  Downloading dateparser-1.1.1-py2.py3-none-any.whl (288 kB)
Collecting boto3==1.*,>=1.19.5
  Downloading boto3-1.24.17-py3-none-any.whl (132 kB)
Collecting click~=7.1

  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting typing-extensions==3.10.0.0
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting tomlkit==0.7.2
  Downloading tomlkit-0.7.2-py2.py3-none-any.whl (32 kB)
Collecting jmespath~=0.10.0
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting regex==2021.9.30
  Downloading regex-2021.9.30-cp39-cp39-win_amd64.whl (273 kB)
Collecting Flask~=1.1.2
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
Collecting PyYAML~=5.3
  Downloading PyYAML-5.4.1-cp39-cp39-win_amd64.whl (213 kB)
Collecting chevron~=0.12
  Downloading chevron-0.14.0-py3-none-any.whl (11 kB)
Collecting watchdog==2.1.2
  Downloading watchdog-2.1.2-py3-none-win_amd64.whl (74 kB)

  WARNING: The script wsdump.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script watchmedo.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flask.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dateparser-download.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script cookiecutter.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script chevron.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script lambda-builders.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sam.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqt5<5.13, which is not installed.
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.1 requires ruamel-yaml, which is not installed.

Requirement already satisfied: wheel in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-lambda-builders==1.17.0->aws-sam-cli) (0.37.0)
Requirement already satisfied: setuptools in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-lambda-builders==1.17.0->aws-sam-cli) (58.0.4)
Requirement already satisfied: six~=1.11 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-lambda-builders==1.17.0->aws-sam-cli) (1.16.0)
Requirement already satisfied: jsonschema~=3.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-sam-translator==1.46.0->aws-sam-cli) (3.2.0)
Collecting botocore<1.28.0,>=1.27.17
  Downloading botocore-1.27.17-py3-none-any.whl (8.9 MB)
Collecting s3transfer<0.7.0,>=0.6.0
  Downloading s3transfer-0.6.0-py3-none-any.whl (79 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests==2.25.1->aws-sam-cli) (4.0.0)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests==2.25.1->aws-sam-cli) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests==2.25.1->aws-sam-cli) (2022.6.15)
Collecting tzdata
  Downloading tzdata-2022.1-py2.py3-none-any.whl (339 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from botocore<1.28.0,>=1.27.17->boto3==1.*,>=1.19.5->aws-sam-cli) (2.8.2)
Requirement already satisfied: poyo>=0.5.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli) (0.5.0)
Requirement already satisfied: jinja2-time>=0.2.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli) (0.2.0)
Collecting Jinja2<3.0.0
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Requirement already satisfied: python-slugify>=4.0.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli) (5.0.2)
Collecting cookiecutter~=1.7.2
  Downloading cookiecutter-1.7.3-py2.py3-none-any.whl (34 kB)
Requirement already satisfied: binaryornot>=0.4.4 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli) (0.4.4)
Requirement already satisfied: Jinja2<4.0.0,>=2.7 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli) (3.0.3)
Requirement already satisfied: pytz in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from dateparser~=1.0->aws-sam-cli) (2022.1)
Collecting pypiwin32==223
  Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting websocket-client>=0.32.0
  Downloading websocket_client-1.3.3-py3-none-any.whl (54 kB)
Requirement already satisfied: pywin32>=223 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pypiwin32==223->docker~=4.2.0->aws-sam-cli) (228)
Collecting itsdangerous<2.0,>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Werkzeug<2.0,>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Requirement already satisfied: arrow in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jinja2-time>=0.2.0->cookiecutter~=1.7.2->aws-sam-cli) (0.13.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jsonschema~=3.2->aws-sam-translator==1.46.0->aws-sam-cli) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jsonschema~=3.2->aws-sam-translator==1.46.0->aws-sam-cli) (0.18.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from python-slugify>=4.0.0->cookiecutter~=1.7.2->aws-sam-cli) (1.3)
Installing collected packages: jmespath, botocore, tzdata, s3transfer, Jinja2, idna, Werkzeug, websocket-client, tzlocal, requests, regex, PyYAML, pypiwin32, itsdangerous, click, boto3, watchdog, typing-extensions, tomlkit, serverlessrepo, Flask, docker, dateparser, cookiecutter, chevron, aws-sam-translator, aws-lambda-builders, aws-sam-cli
Successfully installed Flask-1.1.4 Jinja2-2.11.3 PyYAML-5.4.1 Werkzeug-1.0.1 aws-lambda-builders-1.17.0 aws-sam-cli-1.52.0 aws-sam-translator-1.46.0 boto3-1.24.17 botocore-1.27.17 chevron-0.14.0 click-7.1.2 cookiecutter-1.7.3 dateparser-1.1.1 docker-4.2.2 idna-2.10 itsdangerous-1.1.0 jmespath-0.10.0 pypiwin32-223 regex-2021.9.30 requests-2.25.1 s3transfer-0.6.0 serverlessrepo-0.1.10 tomlkit-0.7.2 typing-extensions-3.10.0.0 tzdata-2022.1 tzlocal-3.0 watchdog-2.1.2 websocket-client-1.3.3

In [21]:
pip install --user aws-sam-cli==1.37.0

Collecting aws-sam-cli==1.37.0
  Downloading aws_sam_cli-1.37.0-py3-none-any.whl (5.0 MB)
Requirement already satisfied: requests==2.25.1 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (2.25.1)
Requirement already satisfied: typing-extensions==3.10.0.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (3.10.0.0)
Requirement already satisfied: click~=7.1 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (7.1.2)
Collecting aws-lambda-builders==1.10.0
  Downloading aws_lambda_builders-1.10.0-py3-none-any.whl (102 kB)
Requirement already satisfied: docker~=4.2.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (4.2.2)
Requirement already satisfied: tomlkit==0.7.2 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (0.7.2)
Requirement already satisfied: Flask~=1.1.2 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (1.1.4)
Requirement already satisfied: regex==2021.9.30 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (2021.9.30)
Requirement already satisfied: PyYAML~=5.3 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (5.4.1)
Requirement already satisfied: jmespath~=0.10.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (0.10.0)
Requirement already satisfied: tzlocal==3.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (3.0)
Requirement already satisfied: dateparser~=1.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (1.1.1)
Requirement already satisfied: cookiecutter~=1.7.2 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (1.7.3)
Collecting aws-sam-translator==1.42.0
  Downloading aws_sam_translator-1.42.0-py3-none-any.whl (216 kB)
Requirement already satisfied: chevron~=0.12 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (0.14.0)
Requirement already satisfied: watchdog==2.1.2 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (2.1.2)
Requirement already satisfied: boto3==1.*,>=1.18.32 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (1.24.17)
Requirement already satisfied: serverlessrepo==0.1.10 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from aws-sam-cli==1.37.0) (0.1.10)
Requirement already satisfied: setuptools in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-lambda-builders==1.10.0->aws-sam-cli==1.37.0) (58.0.4)
Requirement already satisfied: wheel in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-lambda-builders==1.10.0->aws-sam-cli==1.37.0) (0.37.0)
Requirement already satisfied: six~=1.11 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-lambda-builders==1.10.0->aws-sam-cli==1.37.0) (1.16.0)
Requirement already satisfied: jsonschema~=3.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from aws-sam-translator==1.42.0->aws-sam-cli==1.37.0) (3.2.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from boto3==1.*,>=1.18.32->aws-sam-cli==1.37.0) (0.6.0)
Requirement already satisfied: botocore<1.28.0,>=1.27.17 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from boto3==1.*,>=1.18.32->aws-sam-cli==1.37.0) (1.27.17)
Requirement already satisfied: idna<3,>=2.5 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from requests==2.25.1->aws-sam-cli==1.37.0) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests==2.25.1->aws-sam-cli==1.37.0) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests==2.25.1->aws-sam-cli==1.37.0) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from requests==2.25.1->aws-sam-cli==1.37.0) (2022.6.15)
Requirement already satisfied: tzdata in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from tzlocal==3.0->aws-sam-cli==1.37.0) (2022.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from botocore<1.28.0,>=1.27.17->boto3==1.*,>=1.18.32->aws-sam-cli==1.37.0) (2.8.2)
Requirement already satisfied: jinja2-time>=0.2.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (0.2.0)
Requirement already satisfied: Jinja2<4.0.0,>=2.7 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (2.11.3)
Requirement already satisfied: python-slugify>=4.0.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (5.0.2)
Requirement already satisfied: poyo>=0.5.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (0.5.0)
Requirement already satisfied: binaryornot>=0.4.4 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (0.4.4)
Requirement already satisfied: pytz in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from dateparser~=1.0->aws-sam-cli==1.37.0) (2022.1)
Requirement already satisfied: websocket-client>=0.32.0 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from docker~=4.2.0->aws-sam-cli==1.37.0) (1.3.3)
Requirement already satisfied: pypiwin32==223 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from docker~=4.2.0->aws-sam-cli==1.37.0) (223)
Requirement already satisfied: pywin32>=223 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from pypiwin32==223->docker~=4.2.0->aws-sam-cli==1.37.0) (228)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from Flask~=1.1.2->aws-sam-cli==1.37.0) (1.1.0)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in c:\users\riddhi bhogaonkar\appdata\roaming\python\python39\site-packages (from Flask~=1.1.2->aws-sam-cli==1.37.0) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from Jinja2<4.0.0,>=2.7->cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (2.0.1)
Requirement already satisfied: arrow in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jinja2-time>=0.2.0->cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (0.13.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jsonschema~=3.2->aws-sam-translator==1.42.0->aws-sam-cli==1.37.0) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from jsonschema~=3.2->aws-sam-translator==1.42.0->aws-sam-cli==1.37.0) (0.18.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\riddhi bhogaonkar\anaconda3\lib\site-packages (from python-slugify>=4.0.0->cookiecutter~=1.7.2->aws-sam-cli==1.37.0) (1.3)
Installing collected packages: aws-sam-translator, aws-lambda-builders, aws-sam-cli
  Attempting uninstall: aws-sam-translator
    Found existing installation: aws-sam-translator 1.46.0
    Uninstalling aws-sam-translator-1.46.0:
      Successfully uninstalled aws-sam-translator-1.46.0
  Attempting uninstall: aws-lambda-builders
    Found existing installation: aws-lambda-builders 1.17.0
    Uninstalling aws-lambda-builders-1.17.0:
      Successfully uninstalled aws-lambda-builders-1.17.0
  Attempting uninstall: aws-sam-cli
    Found existing installation: aws-sam-cli 1.52.0
    Uninstalling aws-sam-cli-1.52.0:
      Successfully uninstalled aws-sam-cli-1.52.0
Successfully installed aws-lambda-builders-1.10.0 aws-sam-cli-1.37.0 aws-sam-translator-1.42.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script lambda-builders.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sam.exe is installed in 'C:\Users\Riddhi Bhogaonkar\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.